version: 0.2

phases:
    install:
       commands:
        - chmod 770 gradlew
        - ./FanOutConfigurator config.yaml
    build:
      commands:
    post_build:
      commands:
artifacts:
  files:
    - '**/*'
