version: 0.2

phases:
    install:
       commands:
        - ls -al
        - env
        - ./FanOutConfigurator config.yaml
    build:
      commands:
    post_build:
      commands:
artifacts:
  files:
    - '**/*'
