version: 0.2

phases:
    install:
       commands:
        - ls -al
        - chmod 770 FanOutConfigurator
        - ./FanOutConfigurator ./config.yaml
    build:
      commands:
    post_build:
      commands:
artifacts:
  files:
    - '**/*'
