---
FanOutName: KinesisFanOut
Mappings:
- ID: DriverToSHAFanOut
  SourceType: kinesis
  SourceARN: arn:aws:kinesis:eu-central-1:694487085170:stream/FanoutSource
  DestinationARN: arn:aws:kinesis:eu-central-1:260069633584:stream/KinesisFanOutDestination
  DestinationRoleARN: arn:aws:iam::260069633584:role/KinesisFanOutCrossAccount
  Active: true
- ID: DriverToPAFanOut2
  SourceType: kinesis
  SourceARN: arn:aws:kinesis:eu-central-1:799917552027:stream/KinesisFanOutSource
  DestinationARN: arn:aws:kinesis:eu-central-1:240069633584:stream/KinesisFanOutDestination
  DestinationRoleARN: arn:aws:iam::240069633584:role/KinesisFanOutCrossAccount
